version: '3.9'

services:

  teleport:
    image: teleport
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SGX=1  # Enable SGX support
    env_file: "private.env"
    volumes:
      - ./save_dir:/workdir/save_dir  # Persistent data storage
      - ./untrustedhost:/workdir/untrustedhost  # Untrusted host interactions
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket  # SGX architectural enclave service manager socket
    devices:
      - /dev/sgx_enclave  # SGX enclave device
      - /dev/sgx_provision  # SGX provisioning device

