# APP_URL: The URL where the Teleport service is hosted. This varies depending on the environment:
APP_URL = "localhost:8000"
# TEE_URL: The URL where the Trusted Execution Environment (TEE) is hosted.
TEE_URL = "http://localhost:3000"
# WS_RPC_URL: WebSocket URL for the blockchain node provider
WS_RPC_URL = "wss://base-sepolia.g.alchemy.com/v2/"
# RPC_URL: HTTP URL for the blockchain node provider
RPC_URL = "https://base-sepolia.g.alchemy.com/v2/"
# NFT_ADDRESS: On-chain address of the deployed NFT contract used for minting and managing NFTs
NFT_ADDRESS = "0xB92414bA565D8d49E4aaaB45b78b354516006AF1"
# DB_PATH: the in memory SQLite database file for application state of Axum server
DB_PATH = "db.development.sqlite"
